### ISSUE TITLE
gpt api 사용법 알아오기

### ISSUE THREAD

**Issue by sm227** [sm227/capstoneDesign#3]

**Comment by ddabongdochi** [comment]
import openai

# OpenAI API 키 설정
openai.api_key = 'YOUR_API_KEY'

def summarize_text(input_text):
    # GPT 모델 및 엔진 설정
    model = "text-davinci-003"

    # 요약할 문장 및 추가적인 정보
    prompt = f"요약해줘: {input_text}"

    # GPT 요약 생성 요청
    response = openai.Completion.create(
        engine=model,
        prompt=prompt,
        max_tokens=100,  # 요약의 최대 길이
        temperature=0.5,  # 창의성 조절
        top_p=1.0,  # 선택 확률에 대한 상한선
        n=1  # 생성할 요약의 수
    )

    # 생성된 요약 반환
    summary = response.choices[0].text.strip()
    return summary

**Comment by ddabongdochi** [comment]
import openai

# OpenAI API 키 설정
openai.api_key = 'YOUR_API_KEY'

def summarize_text(input_text):
    # GPT 모델 및 엔진 설정
    model = "text-davinci-003"

    # 요약할 문장 및 추가적인 정보
    prompt = f"요약해줘: {input_text}"

    # GPT 요약 생성 요청
    response = openai.Completion.create(
        engine=model,
        prompt=prompt,
        max_tokens=100,  # 요약의 최대 길이
        temperature=0.5,  # 창의성 조절
        top_p=1.0,  # 선택 확률에 대한 상한선
        n=1  # 생성할 요약의 수
    )

    # 생성된 요약 반환
    summary = response.choices[0].text.strip()
    return summary

**Comment by ddabongdochi** [comment]
`import openai

# OpenAI API 키 설정
openai.api_key = 'YOUR_API_KEY'

def summarize_text(input_text):
    # GPT 모델 및 엔진 설정
    model = "text-davinci-003"

    # 요약할 문장 및 추가적인 정보
    prompt = f"요약해줘: {input_text}"

    # GPT 요약 생성 요청
    response = openai.Completion.create(
        engine=model,
        prompt=prompt,
        max_tokens=100,  # 요약의 최대 길이
        temperature=0.5,  # 창의성 조절
        top_p=1.0,  # 선택 확률에 대한 상한선
        n=1  # 생성할 요약의 수
    )

    # 생성된 요약 반환
    summary = response.choices[0].text.strip()
    return summary`

**Comment by ddabongdochi** [comment]
import openai

# OpenAI API 키 설정
openai.api_key = 'YOUR_API_KEY'

def summarize_text(input_text):
    # GPT 모델 및 엔진 설정
    model = "text-davinci-003"

    # 요약할 문장 및 추가적인 정보
    prompt = f"요약해줘: {input_text}"

    # GPT 요약 생성 요청
    response = openai.Completion.create(
        engine=model,
        prompt=prompt,
        max_tokens=100,  # 요약의 최대 길이
        temperature=0.5,  # 창의성 조절
        top_p=1.0,  # 선택 확률에 대한 상한선
        n=1  # 생성할 요약의 수
    )

    # 생성된 요약 반환
    summary = response.choices[0].text.strip()
    return summary

**Comment by ddabongdochi** [comment]
input_text에 유튜브 스크립트 넣으면 아마 될 것 같습니다. 
공부 더 하고 오겠습니다.. 총총...

**Comment by ddabongdochi** [comment]
첫 댓글 다 코드인데 맘대로 형식 정해버리네..

**Comment by sm227** [comment]
와 대박!!!! 고생했어요 😘

**Comment by hyeon031** [comment]
`
ㅇㅇㅇ
`

**Comment by hyeon031** [comment]
```
ㅓㅓㅓ
djdjd
djdj
```

**Comment by sm227** [comment]
굿 최고에용 ~ 👍

**Comment by sm227** [comment]
> ### 김규현 gpt api 정리
> https://opalescent-newt-d59.notion.site/GPT-API-6b3e5ba8c2a64a2b80387ecbbcefeee0?pvs=4

.
